# Generated by Django 5.1.6 on 2025-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO assessments_assessmentquestion (
                id,
                question_type,
                question,
                required,
                [order],
                assessment_id
            ) SELECT
                    id,
                    question_type,
                    question,
                    required,
                    1,
                    assessment_id
                FROM
                    landing_assessmentquestion;

            INSERT INTO assessments_assessment (
                    id,
                    title,
                    due_date,
                    published,
                    course_id
                )
                SELECT
                    id,
                    title,
                    due_date,
                    published,
                    course_id
                FROM
                    landing_assessment;
            """, reverse_sql="""
                INSERT INTO landing_assessment (
                        id,
                        title,
                        due_date,
                        published,
                        course_id
                    )
                    SELECT
                        id,
                        title,
                        due_date,
                        published,
                        course_id
                    FROM
                        assessments_assessment;
        """)
    ]
