# Generated by Django 5.1.6 on 2025-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert'), ('free', 'Free Response'), ('team_member', 'Team Member Selection')], max_length=20),
        ),
    ]
