# Generated by Django 5.1.7 on 2025-04-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_alter_assessmentquestion_question_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="allow_self_assessment",
            field=models.BooleanField(default=False),
        ),
    ]
