# Generated by Django 5.1.6 on 2025-04-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessmentquestion_question_type'),
        ('assessments', '0005_assessment_allow_self_assessment'),
    ]

    operations = [
    ]
