# Generated by Django 5.1.6 on 2025-04-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_merge_20250414_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='published',
        ),
        migrations.AddField(
            model_name='assessment',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
