# Generated by Django 5.1.6 on 2025-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_assessment_published_assessment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='due_soon_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='publish_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
