# Generated by Django 5.1.6 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assessment_due_soon_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='responses_published',
            field=models.BooleanField(default=False),
        ),
    ]
