# Generated by Django 5.1.6 on 2025-03-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='Spring', max_length=40),
            preserve_default=False,
        ),
    ]
