# Generated by Django 5.1.6 on 2025-03-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_course_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['course__name', 'name']},
        ),
    ]
