# Generated by Django 5.1.6 on 2025-03-31 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_assessment_assessmentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='landing.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
