# Generated by Django 5.1.6 on 2025-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_assessment_course_assessment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
