# Generated by Django 5.1.6 on 2025-04-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_assessmentquestion_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
