# Generated by Django 5.1.6 on 2025-04-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_assessment_due_date'),
        ('assessments', '0002_copy_old_assessments')
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
    ]
