# Generated by Django 5.1.6 on 2025-03-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', 'name']},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
