# Generated by Django 5.1.6 on 2025-03-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_remove_user_course_alter_user_options_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailAddress',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
