# Generated by Django 5.1.6 on 2025-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_adminemailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailaddress',
            name='email',
            field=models.EmailField(help_text='Email address of an admin or professor', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
