# Generated by Django 5.1.6 on 2025-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_alter_adminemailaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=10),
        ),
    ]
