# Generated by Django 5.1.6 on 2025-03-28 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('oauth', '0007_course_remove_user_last_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='course',
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='landing.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='landing.team'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
