# Generated by Django 5.1.6 on 2025-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
    ]
