# Generated by Django 5.1.6 on 2025-03-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_alter_user_role'),
        ('oauth', '0008_remove_team_course_alter_user_course_alter_user_team_and_more'),
    ]

    operations = [
    ]
