# Generated by Django 5.1.6 on 2025-04-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0008_assessment_due_soon_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almost_due_sent', models.BooleanField()),
                ('publish_sent', models.BooleanField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='assessments.assessment')),
            ],
        ),
    ]
